### ISSUE TITLE
Charts in for loop have the same value 

### ISSUE THREAD

**Issue by xibman** [weizhenye/vue-highcharts#14]
Hi @weizhenye ,

i found a small bug i think, if you use a loop to show differents chart, they all have the same value: https://jsfiddle.net/z11fe07p/835/

With view of data: https://jsfiddle.net/z11fe07p/836/

**Comment by weizhenye** [comment]
That's because you merge data to `gaugeDefault` every time, which is passed by reference.

Try `_.merge({}, gaugeDefault, {/* your data */})`, notes the first argument is a new object `{}`.

I'm not very familiar with `_.merge`, but I guess it behaves like `Object.assign`, after merging its property may still referencing. So a better way is writing a function that returns `gaugeDefault` literally, then `_.merge({}, generateGaugeDefault(), {/* your data */})`

**Comment by xibman** [comment]
this option was good: _.merge({}, gaugeDefault, {/* your data */})

Thanks a lot !!!
